@echo off
echo [SavorSync] Deteniendo procesos de Dart y Java...
taskkill /F /IM dart.exe /T 2>nul
taskkill /F /IM java.exe /T 2>nul
echo [SavorSync] Limpiando cache de Flutter...
cd mobile
call flutter clean
echo [SavorSync] Obteniendo dependencias...
call flutter pub get
echo [SavorSync] Iniciando Aplicacion en el dispositivo...
call flutter run
pause
